export type PaymentStatus = "UNPAID" | "GUEST_REPORTED" | "CONFIRMED" | "FAILED" | "REFUNDED";
export type SplitStatus = "DRAFT" | "RECEIPT_CAPTURED" | "REVIEW_REQUIRED" | "READY_TO_SHARE" | "CLAIMING" | "ALL_ITEMS_ASSIGNED" | "AWAITING_PAYMENT" | "SETTLED";
